Add Tables
Booze33/vet-clinic pull request #3
Opened 2023-06-07 23:11 UTC by Booze33

<h1>Hello</h1>
<h2>In today's project...</h2>

- Create a table named owners and species
- Modify animals table
- Insert the following data into the owners and species table

<img src=https://github.com/Booze33/vet-clinic/assets/99689722/81f42549-3ffc-4569-b38b-8063b0b81f6a >

2023-06-07 23:27 UTC, alexander16108 requested changes
Hi @alvaroiporre , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/mNLh4BQKRrNQbFbuCF/giphy.gif"/>

## Highlights
✔️ Descriptive Readme file
✔️ Good PR
✔️ passing linters

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 23:27 UTC, alexander16108 commented on queries.sql
> +SELECT full_name, COUNT(*) AS animal_count FROM owners O JOIN animals ON O.id = owner_id GROUP BY full_name ORDER BY animal_count DESC LIMIT 1;
#### please as requested add the screenshot of the following queries to your PR description 

- What animals belong to Melody Pond?
- List of all animals that are Pokemon (their type is Pokemon).
- List all owners and their animals, remember to include those that don't own any animal.
- How many animals are there per species
- List all Digimon owned by Jennifer Orwell.
- List all animals owned by Dean Winchester that haven't tried to escape.
- Who owns the most animals? 

#### Currently, there is a screenshot for three queries but 

- the first ones do not show the queries input
- the second and third have incorrect results the total number of animals is 10 so the numbers sum of both species of animals ought to be 10 
- bob owns two animals and `'Jennifer Orwell'` owns two as well

cheers and good luck 🍀

2023-06-07 23:27 UTC, alexander16108 requested changes
Hi @alvaroiporre , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/mNLh4BQKRrNQbFbuCF/giphy.gif"/>

## Highlights
✔️ Descriptive Readme file
✔️ Good PR
✔️ passing linters

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 10:39 UTC, amejid approved these changes
Hi @Booze33, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/RltjLEzzB87ErJdxHz/giphy.gif"/>

## Highlights
- Correct workflow :heavy_check_mark: 
- SQL organized in separate files :heavy_check_mark: 
- Queries returning correct results :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 16:27 UTC, merged